apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: who-goes-to-try-combined
  namespace: who-goes-to-try
  annotations:
    # Mengaktifkan pembuatan sertifikat otomatis [cite: 547, 592]
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - who-goes-to-try.hackathon.sev-2.com
      # Nama rahasia untuk menyimpan sertifikat [cite: 595]
      secretName: who-goes-to-try-tls-cert
  rules:
    - host: who-goes-to-try.hackathon.sev-2.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: who-goes-to-try-backend
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: who-goes-to-try-frontend
                port:
                  number: 80
